language: php
php:
  - "7.1"
  - "7.0"
  - "5.6"


addons:
  hosts:
    - mysql-container
    - postgres-container
    - mongodb-container
    - mssql-container

services:
  - docker

before_install:
  - sudo service mysql stop || echo "mysql not stopped"
  - sudo service postgresql stop || echo "postgresql not stopped"
  - node_modules/.bin/usdocker --refresh
#  - node_modules/.bin/usdocker mssql up
  - node_modules/.bin/usdocker --no-link postgres up
  - node_modules/.bin/usdocker --no-link mysql up
  - node_modules/.bin/usdocker --no-link mongodb up
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini


install:
  - php -i
  - composer install

script: 
  - vendor/bin/phpunit
  - vendor/bin/phpunit testsdb/PdoSqliteTest.php
  - vendor/bin/phpunit testsdb/MongoDbDriverTest.php
  - vendor/bin/phpunit testsdb/PdoMySqlTest.php
  - vendor/bin/phpunit testsdb/PdoPostgresTest.php
#  - vendor/bin/phpunit testsdb/PdoDblibTest.php
